routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('gallery/json_data', '\App\Http\Controllers\GalleryController@jsonData')->name('gallery.json_data');
Route::resource('gallery', GalleryController::class);

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = 'galleries';

    protected $fillable = ['title', 'caption', 'image', 'mime_type', 'original_name', 'file_size'];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/GalleryController.php
<?php

namespace App\Http\Controllers;

use App\Gallery;
use App\Helpers\Helper;
use App\Http\Requests\GalleryRequest;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;
use Yajra\Datatables\Facades\Datatables;

class GalleryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('gallery.index');
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function jsonData(Request $request)
    {
        if( ! $request->ajax())
        {
            return redirect('/gallery');
        }

        $model = Gallery::query();
        $actions = 'gallery.datatables.actions';

        return Datatables::eloquent($model)
            ->addColumn('actions', $actions)
            ->rawColumns(['actions'])
            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('gallery.form');
    }

    /**
     * @param GalleryRequest $galleryRequest
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(GalleryRequest $galleryRequest)
    {
        ini_set('memory_limit','1024M');
        $fileIdWithExtension = $this->_uploadImage($galleryRequest);
        $file = $galleryRequest->file('image');
        $gallery = Gallery::create([
           'title' => $galleryRequest->input('title'),
            'caption' => $galleryRequest->input('caption'),
            'image' => $fileIdWithExtension,
            'original_name' => $file->getClientOriginalName(),
            'mime_type' => $file->getMimeType(),
            'file_size' => Helper::formatBytes($file->getSize())
        ]);

        return redirect()->route('gallery.edit', ['id' => $gallery->id])->with('message', 'La imagen se ha creado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Gallery::find($id);
        return view('gallery.detail', compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $model = Gallery::find($id);
        $editable = true;
        return view('gallery.form', compact('model', 'editable'));
    }

    /**
     * @param GalleryRequest $galleryRequest
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(GalleryRequest $galleryRequest, $id)
    {
        $gallery = Gallery::findOrFail($id);

        if($galleryRequest->file('image'))
        {
            Helper::removeImages($gallery);

            $fileIdWithExtension = $this->_uploadImage($galleryRequest);
            $file = $galleryRequest->file('image');

            $gallery->fill([
                'title' => $galleryRequest->input('title'),
                'caption' => $galleryRequest->input('caption'),
                'image' => $fileIdWithExtension,
                'original_name' => $file->getClientOriginalName(),
                'mime_type' => $file->getMimeType(),
                'file_size' => Helper::formatBytes($file->getSize())
            ])
            ->save();
        }
        else
        {
            $gallery->fill([
                'title' => $galleryRequest->input('title'),
                'caption' => $galleryRequest->input('caption'),
            ])
            ->save();
        }
        return back()->with('message', 'Imagen actualizada correctamente');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        $galleryId = $request->input('id');
        $gallery = Gallery::find($galleryId);

        if($gallery->image)
        {
            Helper::removeImages($gallery);
        }
        $gallery->delete();
        return response()->json(['res' => 'success'], 200);
    }

    /**
     * @param GalleryRequest $galleryRequest
     * @return string
     */
    private function _uploadImage(GalleryRequest $galleryRequest)
    {
        $file = $galleryRequest->file('image');
        $uniqueId = uniqid();
        $extension = $file->getClientOriginalExtension();
        $fileIdWithExtension = sprintf('%s.%s', $uniqueId, $extension);

        foreach(config('constants.IMAGE_SIZES') as $imageSize)
        {
            if(!\File::isDirectory(public_path('uploads' . DIRECTORY_SEPARATOR . $imageSize[2])))
            {
                \File::makeDirectory(public_path('uploads' . DIRECTORY_SEPARATOR . $imageSize[2]));
            }

            Image::make($file)->resize($imageSize[0], $imageSize[1], function($constraint)
            {
                $constraint->aspectRatio();
            })
            ->save(sprintf('%s/%s/%s', 'uploads',  $imageSize[2], $fileIdWithExtension));
        }

        $watermark = Image::make(public_path('uploads/watermarks/cdw.png'));
        $img = Image::make($file);
        $img->insert($watermark, 'bottom-right', 10, 10);
        $img->save(sprintf('%s/%s', 'uploads/gallery', $fileIdWithExtension));

        return $fileIdWithExtension;
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/gallery/datatables/actions.blade.php
@include('partials.datatables.base_actions', ['edit_route' => 'gallery.edit', 'detail_route' => 'gallery.show','destroy_route' => 'gallery.destroy', 'id' => $id])

resources/views/gallery/detail.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-lg-12">
        @foreach(config('constants.IMAGE_SIZES') as $imageSize)
            <div class="well">
                {!! Html::image(sprintf('%s/%s/%s', 'uploads', $imageSize[2], $model->image)) !!}
            </div>
        @endforeach
            {!! Html::image(sprintf('%s/%s/%s', 'uploads', 'gallery', $model->image)) !!}
    </div>

@endsection

resources/views/gallery/form.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-12">

        @if(isset($editable))
            {!! Form::model($model, ['route' => ['gallery.update', $model->id], 'method' => 'PUT', 'files' => true]) !!}
        @else
            {!! Form::open(['route' => 'gallery.store', 'files' => true]) !!}
        @endif


        @if(isset($editable))
            @if($errors->first('image') && ! $model->image)
                <div class="col-md-4 form-group has-error">
            @else
                <div class="form-group col-md-4">
            @endif
                <label class="btn btn-default btn-file">
                    Buscar imagen{!! Form::file('image', ['style' => 'display: none']) !!}
                </label>
                <span class="help-block">{{ $errors->first('image') }}</span>
            </div>
        @else
            @if($errors->first('image'))
                <div class="col-md-4 form-group has-error">
            @else
                <div class="form-group col-md-4">
            @endif
                <label class="btn btn-default btn-file">
                    Buscar imagen{!! Form::file('image', ['style' => 'display: none', 'class']) !!}
                </label>
                <span class="help-block">{{ $errors->first('image') }}</span>
            </div>
        @endif

        <div id="container-logo" class="col-md-12" style="display: none">
            @if(isset($editable) && $model->image)
                <div class="text-center">
                    {{ Html::image('uploads/gallery/' . $model->image, '', ["id" => "gallery-img"]) }}
                </div>
            @else
                <img style="padding: 10px;" class="img-responsive" id="gallery-img" src="#" />
            @endif
        </div>

        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('title', 'Título') }}
                {{ Form::input('text', 'title', old('title'), ['class' => 'form-control']) }}
                @if($errors->first('title'))
                    <div class="has-error">
                        <span class="help-block">{{ $errors->first('title') }}</span>
                    </div>
                @endif
            </div>
        </div>

        <div class="col-md-12">
            <div class="form-group">
                {{ Form::label('caption', 'Descripción de la imagen') }}
                {!! Form::textarea('caption', old('caption'), ['class' => 'form-control', 'rows' => 4]) !!}
                @if($errors->first('title'))
                    <div class="has-error">
                        <span class="help-block">{{ $errors->first('caption') }}</span>
                    </div>
                @endif
            </div>
        </div>

        <div class="col-md-12">
            @if (isset($editable))
                <div class="form-group">
                    {!! Form::submit('Actualizar imagen', ['class' => 'btn btn-success btn-block']) !!}
                </div>
            @else
                <div class="form-group">
                    {!! Form::submit('Dar de alta imagen', ['class' => 'btn btn-success btn-block']) !!}
                </div>
            @endif

            <div class="form-group">
                {!! link_to_route('gallery.index', 'Volver', [], ['class' => 'btn btn-warning btn-block']) !!}
            </div>
        </div>


        {!! Form::close() !!}

    </div>

@endsection

@push('scripts')
<script>
    jQuery(function ()
    {
        @if(isset($editable))
            jQuery('#container-logo').css('display', 'block');
        @endif

        jQuery("input[type=file]").change(function() {
            readURL(this);
        });

        const readURL = (input) => {

            if (input.files && input.files[0]) {
                const reader = new FileReader();

                reader.onload =  (e) => {
                    jQuery('#gallery-img').attr('src', e.target.result)
                    jQuery('#container-logo').css('display', 'block');
                }
                reader.readAsDataURL(input.files[0]);
            }
        };
    })
</script>
@endpush

resources/views/gallery/index.blade.php
@extends('layouts.app')

@push('stylesheets')
{!! Html::style('//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css') !!}
{!! Html::style('//cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css') !!}

<style>
    #gallery-table th, #gallery-table td
    {
        text-align:center;
        vertical-align:middle;
    }
</style>
@endpush

@section('content')

    <div class="col-md-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">
                    Galería
                    <span class="pull-right">
                        <a class="btn btn-primary" href="{{ route('gallery.create') }}">
                            Añadir imagen
                        </a>
                    </span>
                </h3>
            </div>

            <hr />

            <!-- /.box-header -->
            <div class="box-body">
                <table class="table table-striped table-bordered nowrap" cellspacing="0" id="gallery-table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Título</th>
                        <th>Caption</th>
                        <th>Imagen</th>
                        <th width="70">Acciones</th>
                    </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>

@endsection

@push('scripts')

{!! Html::script('//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js') !!}
{!! Html::script('//cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js') !!}

<script>
    var dt;
    jQuery(function()
    {
        dt = jQuery('#gallery-table').DataTable({
            "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.13/i18n/Spanish.json"
            },
            processing: true,
            serverSide: false,
            ajax: '{!! route('gallery.json_data') !!}',
            columns: [
                { data: 'id', name: 'id', visible: false },
                { data: 'title', name: 'title' },
                { data: 'caption', name: 'caption', mRender: function(data, type, full)
                {
                    return `${data.substring(0, 70)}...`;
                }},
                { data: 'image', name: 'image' },
                { data: 'actions', name: 'actions', orderable: false }
            ]
        });

        jQuery(document).on('click', '#gallery-table a', function(e)
        {
            if(jQuery(this).data('remove'))
            {
                e.preventDefault();
                removeRow(jQuery(this).data('id'), '{{ route('gallery.destroy', 0) }}', dt)
            }
        });

        function removeRow(id, route, dt)
        {
            jQuery.ajax({
                url: route,
                method: 'DELETE',
                headers: {
                    'x-csrf-token': $('meta[name="csrf-token"]').attr('content'),
                },
                data: {
                    id: id
                },
                success: function (data) {
                    dt.ajax.reload();
                }
            });
        }
    });
</script>
@endpush

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    @stack('stylesheets')
</head>
<body>
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Login</a></li>
                        <li><a href="{{ route('register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @if(session('message'))
        <div class="alert alert-success">
            {{ session('message') }}
        </div>
    @endif

    @yield('content')
</div>

<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@stack('scripts')
</body>
</html>

resources/views/partials/datatables/base_actions.blade.php
@if(isset($detail_route))
    <a href="{{ route($detail_route, [$id]) }}" data-id="{{$id}}" class="btn btn-info">Detalle</a>
@endif

@if(isset($edit_route))
    <a href="{{ route($edit_route, [$id]) }}" data-edit="true" data-id="{{$id}}" class="btn btn-info">Editar</a>
@endif

@if(isset($destroy_route))
    <a href="{{ route($destroy_route, [$id]) }}" data-remove="true" data-id="{{$id}}" class="btn btn-danger">Eliminar</a>
@endif
@stack('datatables_actions')